/**
 * NorthwindManager
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderDto { 
    id: number;
    nrOrderDetails: number;
    readonly orderDateMillis: number;
    readonly requiredDateMillis: number;
    readonly shippedDateMillis: number;
}

