/**
 * NorthwindManager
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderDetailsDto { 
    orderId: number;
    unitPrice: number;
    quantity: number;
    productName: string;
}

