/**
 * NorthwindManager
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SupplierDto { 
    id: number;
    companyName: string;
    contactName?: string | null;
    city?: string | null;
    country?: string | null;
}

